# Generated by Django 6.0.1 on 2026-01-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kycdocument',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='kyc_approved_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kyc_submitted_at',
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_type',
            field=models.CharField(choices=[('ID_CARD', 'ID Card'), ('PASSPORT', 'Passport'), ('DRIVERS_LICENSE', 'Drivers License'), ('PROOF_OF_ADDRESS', 'Proof of Address')], max_length=50),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_transfer_limit',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='kyc_level',
            field=models.CharField(choices=[('LEVEL_0', 'Not Verified'), ('LEVEL_1', 'Basic Verification'), ('LEVEL_2', 'Intermediate Verification'), ('LEVEL_3', 'Full Verification')], default='LEVEL_0', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='monthly_transfer_limit',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('PIN_CHANGE', 'PIN Change'), ('2FA_ENABLED', '2FA Enabled'), ('2FA_DISABLED', '2FA Disabled')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
