# Generated by Django 6.0.1 on 2026-01-29 15:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingsaccount',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='savingsproduct',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='savingstransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='savingstransaction',
            name='description',
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Early withdrawal penalty if applicable', max_digits=12),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('LOCKED', 'Locked'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='savingsproduct',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='savingsproduct',
            name='early_withdrawal_penalty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Penalty percentage for early withdrawal', max_digits=5),
        ),
        migrations.AlterField(
            model_name='savingsproduct',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, help_text='Annual interest rate percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='savingsproduct',
            name='lock_period_days',
            field=models.IntegerField(default=0, help_text='Lock-in period in days (0 for flexible)'),
        ),
        migrations.AlterField(
            model_name='savingsproduct',
            name='minimum_deposit',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='savingsproduct',
            name='product_type',
            field=models.CharField(choices=[('FLEX', 'Flexible Savings'), ('30_DAY', '30-Day Lock'), ('90_DAY', '90-Day Lock'), ('12_PERCENT', '12% Premium')], max_length=20),
        ),
        migrations.AlterField(
            model_name='savingstransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='savingstransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='savingstransaction',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='savingstransaction',
            name='reference',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='savingstransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('INTEREST', 'Interest Credit')], max_length=20),
        ),
    ]
