# Generated by Django 6.0.1 on 2026-01-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeconfiguration',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('CRYPTO_BUY', 'Crypto Buy'), ('CRYPTO_SELL', 'Crypto Sell'), ('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('SAVINGS_DEPOSIT', 'Savings Deposit'), ('SAVINGS_WITHDRAWAL', 'Savings Withdrawal'), ('INTEREST_CREDIT', 'Interest Credit')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling')], max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('CRYPTO_BUY', 'Crypto Buy'), ('CRYPTO_SELL', 'Crypto Sell'), ('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('SAVINGS_DEPOSIT', 'Savings Deposit'), ('SAVINGS_WITHDRAWAL', 'Savings Withdrawal'), ('INTEREST_CREDIT', 'Interest Credit')], max_length=30),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling')], default='USD', max_length=3),
        ),
    ]
