# Currency codes
CURRENCY_USD = 'USD'
CURRENCY_EUR = 'EUR'
CURRENCY_GBP = 'GBP'
CURRENCY_KES = 'KES'

CURRENCY_CHOICES = [
    (CURRENCY_USD, 'US Dollar'),
    (CURRENCY_EUR, 'Euro'),
    (CURRENCY_GBP, 'British Pound'),
    (CURRENCY_KES, 'Kenyan Shilling'),
]

# Transaction types
TRANSACTION_DEPOSIT = 'DEPOSIT'
TRANSACTION_WITHDRAWAL = 'WITHDRAWAL'
TRANSACTION_TRANSFER = 'TRANSFER'
TRANSACTION_CRYPTO_BUY = 'CRYPTO_BUY'
TRANSACTION_CRYPTO_SELL = 'CRYPTO_SELL'
TRANSACTION_LOAN_DISBURSEMENT = 'LOAN_DISBURSEMENT'
TRANSACTION_LOAN_REPAYMENT = 'LOAN_REPAYMENT'
TRANSACTION_SAVINGS_DEPOSIT = 'SAVINGS_DEPOSIT'
TRANSACTION_SAVINGS_WITHDRAWAL = 'SAVINGS_WITHDRAWAL'
TRANSACTION_INTEREST_CREDIT = 'INTEREST_CREDIT'

TRANSACTION_TYPE_CHOICES = [
    (TRANSACTION_DEPOSIT, 'Deposit'),
    (TRANSACTION_WITHDRAWAL, 'Withdrawal'),
    (TRANSACTION_TRANSFER, 'Transfer'),
    (TRANSACTION_CRYPTO_BUY, 'Crypto Buy'),
    (TRANSACTION_CRYPTO_SELL, 'Crypto Sell'),
    (TRANSACTION_LOAN_DISBURSEMENT, 'Loan Disbursement'),
    (TRANSACTION_LOAN_REPAYMENT, 'Loan Repayment'),
    (TRANSACTION_SAVINGS_DEPOSIT, 'Savings Deposit'),
    (TRANSACTION_SAVINGS_WITHDRAWAL, 'Savings Withdrawal'),
    (TRANSACTION_INTEREST_CREDIT, 'Interest Credit'),
]

# Transaction status
TRANSACTION_PENDING = 'PENDING'
TRANSACTION_COMPLETED = 'COMPLETED'
TRANSACTION_FAILED = 'FAILED'
TRANSACTION_CANCELLED = 'CANCELLED'

TRANSACTION_STATUS_CHOICES = [
    (TRANSACTION_PENDING, 'Pending'),
    (TRANSACTION_COMPLETED, 'Completed'),
    (TRANSACTION_FAILED, 'Failed'),
    (TRANSACTION_CANCELLED, 'Cancelled'),
]

# KYC levels
KYC_LEVEL_0 = 'LEVEL_0'
KYC_LEVEL_1 = 'LEVEL_1'
KYC_LEVEL_2 = 'LEVEL_2'
KYC_LEVEL_3 = 'LEVEL_3'

KYC_LEVEL_CHOICES = [
    (KYC_LEVEL_0, 'Not Verified'),
    (KYC_LEVEL_1, 'Basic Verification'),
    (KYC_LEVEL_2, 'Intermediate Verification'),
    (KYC_LEVEL_3, 'Full Verification'),
]

# KYC document types
DOC_TYPE_ID = 'ID_CARD'
DOC_TYPE_PASSPORT = 'PASSPORT'
DOC_TYPE_DRIVERS_LICENSE = 'DRIVERS_LICENSE'
DOC_TYPE_PROOF_OF_ADDRESS = 'PROOF_OF_ADDRESS'

KYC_DOCUMENT_TYPE_CHOICES = [
    (DOC_TYPE_ID, 'ID Card'),
    (DOC_TYPE_PASSPORT, 'Passport'),
    (DOC_TYPE_DRIVERS_LICENSE, 'Drivers License'),
    (DOC_TYPE_PROOF_OF_ADDRESS, 'Proof of Address'),
]

# KYC document status
KYC_STATUS_PENDING = 'PENDING'
KYC_STATUS_APPROVED = 'APPROVED'
KYC_STATUS_REJECTED = 'REJECTED'

KYC_STATUS_CHOICES = [
    (KYC_STATUS_PENDING, 'Pending'),
    (KYC_STATUS_APPROVED, 'Approved'),
    (KYC_STATUS_REJECTED, 'Rejected'),
]

# Savings product types
SAVINGS_FLEX = 'FLEX'
SAVINGS_30_DAY = '30_DAY'
SAVINGS_90_DAY = '90_DAY'
SAVINGS_12_PERCENT = '12_PERCENT'

SAVINGS_PRODUCT_TYPE_CHOICES = [
    (SAVINGS_FLEX, 'Flexible Savings'),
    (SAVINGS_30_DAY, '30-Day Lock'),
    (SAVINGS_90_DAY, '90-Day Lock'),
    (SAVINGS_12_PERCENT, '12% Premium'),
]

# Savings account status
SAVINGS_ACTIVE = 'ACTIVE'
SAVINGS_LOCKED = 'LOCKED'
SAVINGS_CLOSED = 'CLOSED'

SAVINGS_STATUS_CHOICES = [
    (SAVINGS_ACTIVE, 'Active'),
    (SAVINGS_LOCKED, 'Locked'),
    (SAVINGS_CLOSED, 'Closed'),
]

# Loan Status
LOAN_PENDING = 'PENDING'
LOAN_APPROVED = 'APPROVED'
LOAN_REJECTED = 'REJECTED'
LOAN_DISBURSED = 'DISBURSED'
LOAN_ACTIVE = 'ACTIVE'
LOAN_PAID = 'PAID'
LOAN_DEFAULTED = 'DEFAULTED'

LOAN_STATUS_CHOICES = [
    (LOAN_PENDING, 'Pending'),
    (LOAN_APPROVED, 'Approved'),
    (LOAN_REJECTED, 'Rejected'),
    (LOAN_DISBURSED, 'Disbursed'),
    (LOAN_ACTIVE, 'Active'),
    (LOAN_PAID, 'Paid'),
    (LOAN_DEFAULTED, 'Defaulted'),
]

# Fee types
FEE_TYPE_FIXED = 'FIXED'
FEE_TYPE_PERCENTAGE = 'PERCENTAGE'

FEE_TYPE_CHOICES = [
    (FEE_TYPE_FIXED, 'Fixed Amount'),
    (FEE_TYPE_PERCENTAGE, 'Percentage'),
]

# Notification types
NOTIFICATION_TRANSACTION = 'TRANSACTION'
NOTIFICATION_KYC = 'KYC'
NOTIFICATION_LOAN = 'LOAN'
NOTIFICATION_SAVINGS = 'SAVINGS'
NOTIFICATION_SECURITY = 'SECURITY'
NOTIFICATION_SYSTEM = 'SYSTEM'

NOTIFICATION_TYPE_CHOICES = [
    (NOTIFICATION_TRANSACTION, 'Transaction'),
    (NOTIFICATION_KYC, 'KYC'),
    (NOTIFICATION_LOAN, 'Loan'),
    (NOTIFICATION_SAVINGS, 'Savings'),
    (NOTIFICATION_SECURITY, 'Security'),
    (NOTIFICATION_SYSTEM, 'System'),
]

# User activity types
ACTIVITY_LOGIN = 'LOGIN'
ACTIVITY_LOGOUT = 'LOGOUT'
ACTIVITY_PASSWORD_CHANGE = 'PASSWORD_CHANGE'
ACTIVITY_PIN_CHANGE = 'PIN_CHANGE'
ACTIVITY_2FA_ENABLED = '2FA_ENABLED'
ACTIVITY_2FA_DISABLED = '2FA_DISABLED'

ACTIVITY_TYPE_CHOICES = [
    (ACTIVITY_LOGIN, 'Login'),
    (ACTIVITY_LOGOUT, 'Logout'),
    (ACTIVITY_PASSWORD_CHANGE, 'Password Change'),
    (ACTIVITY_PIN_CHANGE, 'PIN Change'),
    (ACTIVITY_2FA_ENABLED, '2FA Enabled'),
    (ACTIVITY_2FA_DISABLED, '2FA Disabled'),
]

# Email status
EMAIL_STATUS_PENDING = 'PENDING'
EMAIL_STATUS_SENT = 'SENT'
EMAIL_STATUS_FAILED = 'FAILED'

EMAIL_STATUS_CHOICES = [
    (EMAIL_STATUS_PENDING, 'Pending'),
    (EMAIL_STATUS_SENT, 'Sent'),
    (EMAIL_STATUS_FAILED, 'Failed'),
]

CURRENCIES = CURRENCY_CHOICES
TRANSACTION_TYPES = TRANSACTION_TYPE_CHOICES
TRANSACTION_STATUS = TRANSACTION_STATUS_CHOICES
STATUS_PENDING = TRANSACTION_PENDING
# KYC level shortcuts
KYC_BASIC = KYC_LEVEL_1
KYC_INTERMEDIATE = KYC_LEVEL_2
KYC_FULL = KYC_LEVEL_3


# Aliases for backward compatibility
STATUS_COMPLETED = TRANSACTION_COMPLETED
STATUS_PENDING = TRANSACTION_PENDING
STATUS_FAILED = TRANSACTION_FAILED

