# Generated by Django 6.0.1 on 2026-01-29 15:25

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0002_alter_feeconfiguration_transaction_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(help_text='e.g., BTC, ETH', max_length=10, unique=True)),
                ('name', models.CharField(help_text='e.g., Bitcoin, Ethereum', max_length=100)),
                ('icon_url', models.URLField(blank=True)),
                ('current_price_usd', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('percent_change_24h', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Crypto Currencies',
                'db_table': 'crypto_currencies',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0E-8'))])),
                ('total_invested_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('average_buy_price', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=20)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to='crypto.cryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crypto_wallets',
                'ordering': ['-balance'],
                'unique_together': {('user', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='CryptoTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('transaction_type', models.CharField(choices=[('CRYPTO_BUY', 'Buy'), ('CRYPTO_SELL', 'Sell')], max_length=20)),
                ('crypto_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_per_unit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('usd_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('total_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='COMPLETED', max_length=20)),
                ('crypto_balance_after', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fiat_balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fiat_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_transactions', to='wallet.wallet')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='crypto.cryptowallet')),
            ],
            options={
                'db_table': 'crypto_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
